const coursesData = {
  courses: [
    {
      id: "learn-figma-from-basic",
      title: "Learn Figma from Basic",
      instructor: "umpaspi studio",
      image: "/assets/courses/figma-basic.jpg",
      lessons: 11,
      duration: "2 hours 30 mins",
      comments: 56,
      rating: 4.5,
      level: "Beginner",
      price: 25,
      students: 3,
    },
    {
      id: "build-digital-asset",
      title: "Build Digital Asset",
      instructor: "umpaspi studio",
      image: "/assets/courses/digital-asset.jpg",
      lessons: 11,
      duration: "2 hours 30 mins",
      comments: 56,
      rating: 4.5,
      level: "Beginner",
      price: 25,
      students: 3,
    },
    {
      id: "the-power-of-big-data",
      title: "The Power of Big Data",
      instructor: "umpaspi studio",
      image: "/assets/courses/big-data.jpg",
      lessons: 11,
      duration: "2 hours 30 mins",
      comments: 56,
      rating: 4.5,
      level: "Beginner",
      price: 25,
      students: 3,
    },
    {
      id: "balancing-productivity",
      title: "Balancing Productivity on the Go",
      instructor: "umpaspi studio",
      image: "/assets/courses/productivity.jpg",
      lessons: 11,
      duration: "2 hours 30 mins",
      comments: 56,
      rating: 4.5,
      level: "Beginner",
      price: 25,
      students: 3,
    },
    {
      id: "mastering-money-manage",
      title: "Mastering Money Management",
      instructor: "umpaspi studio",
      image: "/assets/courses/money-manage.jpg",
      lessons: 11,
      duration: "2 hours 30 mins",
      comments: 56,
      rating: 4.5,
      level: "Beginner",
      price: 25,
      students: 3,
    },
    {
      id: "from-idea-to-startup",
      title: "From Idea to Startup Success",
      instructor: "umpaspi studio",
      image: "/assets/courses/startup.jpg",
      lessons: 11,
      duration: "2 hours 30 mins",
      comments: 56,
      rating: 4.5,
      level: "Beginner",
      price: 25,
      students: 3,
    },
  ],
};

export default coursesData;
